LEFT = 'left'
RIGHT = 'right'
UP = 'up'
DOWN = 'down'

opposite_directions = {LEFT: RIGHT, RIGHT: LEFT, UP: DOWN, DOWN: UP}

HORIZONTAL_MOVES = (LEFT, RIGHT)
VERTICAL_MOVES = (UP, DOWN)

SIDE_DIRECTIONS = {
    LEFT: VERTICAL_MOVES,
    RIGHT: VERTICAL_MOVES,
    UP: HORIZONTAL_MOVES,
    DOWN: HORIZONTAL_MOVES
}
